# Generated by Django 6.0 on 2025-12-11 23:30

import django_ltree.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='path',
            field=django_ltree.fields.PathField(blank=True, null=True, unique=True),
        ),
    ]
